### ISSUE TITLE
コントローラが作成できないバグを解消する

### ISSUE THREAD

**Issue by yh2020** [CircleAround/eventure#7]
Wecomeコントローラを作成しようとしたらエラーが出てしまう。

```
$ bundle exec rails g controller welcome index
/Users/yhayashi/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler/setup (LoadError)
    from /Users/yhayashi/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/spring-1.6.2/lib/spring/commands.rb:33:in `<module:Spring>'
    from /Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/spring-1.6.2/lib/spring/commands.rb:4:in `<top (required)>'
    from /Users/yhayashi/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/yhayashi/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/spring-1.6.2/lib/spring/application.rb:77:in `preload'
    from /Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/spring-1.6.2/lib/spring/application.rb:143:in `serve'
    from /Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/spring-1.6.2/lib/spring/application.rb:131:in `block in run'
    from /Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/spring-1.6.2/lib/spring/application.rb:125:in `loop'
    from /Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/spring-1.6.2/lib/spring/application.rb:125:in `run'
    from /Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/spring-1.6.2/lib/spring/application/boot.rb:18:in `<top (required)>'
    from /Users/yhayashi/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/yhayashi/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from -e:1:in `<main>'
```

ので、解消しましょう。

**Comment by yh2020** [comment]
http://stackoverflow.com/questions/34627385/require-cannot-load-such-file-bundler-setup-loaderror

に解決策が載っていた。
