### ISSUE TITLE
deviseの導入

### ISSUE THREAD

**Issue by yh2020** [CircleAround/eventure#97]
現在は、twitterのログイン機能があるが、メールログインを基本としたいので、deviseを導入する。

メールログインの流れについては別issueで対応。

http://qiita.com/cigalecigales/items/73d7bd7ec59a001ccd74

**Comment by yh2020** [comment]
rake db:migrateをした際に以下のエラーに遭遇。

```
$ bundle exec rake db:migrate
== 20160219073522 AddDeviseToUsers: migrating =================================
-- change_table(:users)
   -> 0.1105s
-- add_index(:users, :email, {:unique=>true})
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::UniqueViolation: ERROR:  could not create unique index "index_users_on_email"
DETAIL:  Key (email)=() is duplicated.
: CREATE UNIQUE INDEX  "index_users_on_email" ON "users"  ("email")/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `async_exec'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `block in execute'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract_adapter.rb:472:in `block in log'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract_adapter.rb:466:in `log'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/postgresql/database_statements.rb:154:in `execute'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/postgresql/schema_statements.rb:477:in `add_index'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:665:in `block in method_missing'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:634:in `block in say_with_time'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:634:in `say_with_time'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:654:in `method_missing'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:416:in `method_missing'
/Users/yhayashi/work/circle_around/eventure/db/migrate/20160219073522_add_devise_to_users.rb:38:in `up'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:571:in `up'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:611:in `exec_migration'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:591:in `block in migrate'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:590:in `migrate'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:768:in `migrate'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:998:in `block in execute_migration_in_transaction'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:1044:in `block in ddl_transaction'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/transactions.rb:220:in `transaction'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:1044:in `ddl_transaction'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:959:in `block in migrate'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:955:in `each'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:955:in `migrate'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:823:in `up'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:801:in `migrate'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
ActiveRecord::RecordNotUnique: PG::UniqueViolation: ERROR:  could not create unique index "index_users_on_email"
DETAIL:  Key (email)=() is duplicated.
: CREATE UNIQUE INDEX  "index_users_on_email" ON "users"  ("email")
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `async_exec'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `block in execute'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract_adapter.rb:472:in `block in log'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract_adapter.rb:466:in `log'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/postgresql/database_statements.rb:154:in `execute'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/postgresql/schema_statements.rb:477:in `add_index'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:665:in `block in method_missing'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:634:in `block in say_with_time'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:634:in `say_with_time'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:654:in `method_missing'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:416:in `method_missing'
/Users/yhayashi/work/circle_around/eventure/db/migrate/20160219073522_add_devise_to_users.rb:38:in `up'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:571:in `up'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:611:in `exec_migration'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:591:in `block in migrate'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:590:in `migrate'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:768:in `migrate'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:998:in `block in execute_migration_in_transaction'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:1044:in `block in ddl_transaction'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/transactions.rb:220:in `transaction'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:1044:in `ddl_transaction'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:959:in `block in migrate'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:955:in `each'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:955:in `migrate'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:823:in `up'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:801:in `migrate'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
PG::UniqueViolation: ERROR:  could not create unique index "index_users_on_email"
DETAIL:  Key (email)=() is duplicated.
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `async_exec'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `block in execute'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract_adapter.rb:472:in `block in log'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract_adapter.rb:466:in `log'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/postgresql/database_statements.rb:154:in `execute'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/postgresql/schema_statements.rb:477:in `add_index'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:665:in `block in method_missing'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:634:in `block in say_with_time'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:634:in `say_with_time'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:654:in `method_missing'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:416:in `method_missing'
/Users/yhayashi/work/circle_around/eventure/db/migrate/20160219073522_add_devise_to_users.rb:38:in `up'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:571:in `up'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:611:in `exec_migration'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:591:in `block in migrate'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:590:in `migrate'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:768:in `migrate'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:998:in `block in execute_migration_in_transaction'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:1044:in `block in ddl_transaction'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/transactions.rb:220:in `transaction'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:1044:in `ddl_transaction'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:959:in `block in migrate'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:955:in `each'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:955:in `migrate'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:823:in `up'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:801:in `migrate'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/Users/yhayashi/work/circle_around/eventure/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

大事なのは、

PG::UniqueViolation: ERROR:  could not create unique index "index_users_on_email"
DETAIL:  Key (email)=() is duplicated.

らへんだと思われるので、調べてみた。

https://github.com/plataformatec/devise/issues/2416
https://github.com/plataformatec/devise/issues/2594

**Comment by yh2020** [comment]
以下を参考にすると、Userモデルの作成時に用いた「add_index :users, [:provider, :uid], unique: true」が問題のようだ。

http://stackoverflow.com/questions/9364925/activeadmin-devise-2-in-existing-but-bare-user-model-not-working

現在コケているマイグレーションファイルでは、

add_index :users, :email,                unique: true
add_index :users, :reset_password_token, unique: true

という部分でインデックスをはっており、ひとまず今回のエラーを回避するために上述の2行をコメントアウトした。
